#! /bin/sh

# Downloading dependencies
source ~/.bashrc
python --version

#-------------------------- Open SSL installation -------------------------

# which returns the number of failed arguments
which openssl

if [[ $? -eq 1 ]]; then
    cd ../../../utils
    python -c "import distributions; distributions.Distributions().getopenssl(ssl)"
    cd -
    # if return code is non-zero then there was an error in the installation
    if [[ $? -eq 0 ]];  then
	echo "compiling ssl  distribution "
	cd ssl
	./config ; sudo make install
	cd ..

	which openssl
	if [[ $? -eq 1 ]]; then
	    echo " Unable to generate library for openssl distribution "
	fi
    else
	echo "unsuccessful installation"
	exit 1
    fi
else
    echo "Found openssl installation no need to install"
fi


#------------------------ mongodb, pymongo ----------------------
which mongod

if [[ $? -eq 1 ]]; then
#    cd ../../../utils
    python -c "import distributions; distributions.Distributions().getmongo(mongodb)"
#    cd -
    if [[ $? -eq 0 ]]; then
	echo " Successful retrieving mongo and pymongo distribution "
	sudo cp -rf mongodb /usr/local/mongodb
    fi

    if [ ! -e "/usr/local/mongodb/bin/mongod" ]; then
	echo "Unable to copy mongodb into /usr/local"
    else
	echo " Able to copy into /usr/local, removing distribution from curr dir "
	sudo rm -rf mongodb*
    fi
else 
    echo  "Found mongod installation no need to install "
fi


#----------------------check pymongo --------------------------
# Checks if loading the library is successful
# for consistency:  0 returns successful import 1 returns unsuccessful import
cd ../server/utils
python -c "import distributions; distributions.Distributions().checkmongo()"
cd -
if [[ $? -eq 0 ]]; then 
    echo " Successful importing pymongo library "
else
    echo " Not successful importing pymongo library "
fi    




#---------------------CherryPy--------------------------
# Checks and retrieves the Cherrypy distribution
# Loads library
# Checks if loading library is successful
cd ../server/utils
python -c "import distributions; distributions.Distributions().checkcherrypy()"
cd -
if [[ $? -eq 0 ]]; then
    echo " Successful in importing the cherrypy library, no need for installation "
else
    cd ../server/utils
    python -c "import distributions; x = distributions.Distributions(); x.getcherrypy('cherrypy')"
    cd -
    if [[ $? -eq 0 ]]; then 
	echo " Successful retrieving the cherrypy distribution "
	cd cherrypy
	sudo python setup.py install
    fi
#--------------Re- Check cherrypy inport -----------------------
    cd ../server/utils
    python -c "import distributions; distributions.Distributions().checkcherrypy()"
    if [[ $? -eq 0 ]]; then
	echo " Successful in importing the cherrypy library "
    else
	echo " Not successful in importing the cherrypy library "
    fi
fi

#-------Generating keys and certificates ---------------

    # Generating the public key of size 2048
if [ ! -e "server.key" ]; then
    echo "Generating the server key of size 2048"
    /usr/local/ssl/bin/openssl genrsa -des3 -out server.key 2048
fi

    # Generating the certificate
if [ ! -e server.key ]; then
    echo "Unable to generate the public key "
    exit 1
else
    if [ ! -e "server.csr" ]; then
    echo "Generating the certificate"
    /usr/local/ssl/bin/openssl req -new -key server.key -out server.csr
    fi
fi

    # Generating the private key
if [ ! -e "server.csr" ]; then
    echo "Unable to generate the private key,  missing server.crt file "	
else
    if [ ! -e "server.crt" ]; then
	echo "Getting private key"
	/usr/local/ssl/bin/openssl x509 -req -days 60 -in server.csr -signkey server.key -out server.crt
    fi
fi


